<?php if ($block->isEnabled("product_page")) : ?>
    <div id="payment-request-button" class="payment-request-button"></div>
    <script>
        require(['StripeIntegration_Payments/js/stripe_payments_express', 'Magento_Customer/js/customer-data'], function(stripeExpress, customerData)
        {
            var cart = customerData.get('cart');
            var initECE = function()
            {
                var locationDetails = {
                    location: 'product',
                    productId: '<?= $block->escapeJs($block->getProductId()); ?>',
                };
                stripeExpress.initStripeExpress(
                    '#payment-request-button',
                    <?= /* @noEscape */ $block->initParams->getWalletParams(); ?>,
                    locationDetails,
                    <?= /* @noEscape */ $block->getButtonConfig(); ?>,
                    stripeExpress.initProductWidget.bind(stripeExpress)
                );
            };
            initECE();

            cart.subscribe(function ()
            {
                // Wait for Magento to commit the changes before re-initializing the ECE
                setTimeout(function(){
                    stripeExpress.log("onCartUpdated");
                    initECE();
                }, 500);
            });
        });
    </script>
<?php endif; ?>
