<?php
/**
 * Copyright © 2020 MageBig, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/**
 * @var $block MageBig\Shopbybrand\Block\Brand\AllBrands
 */
$pageInfo = $block->getPageInfo();
$displayBrandSearch = (bool)$pageInfo->getData('display_brand_search');
?>

<div class="brand-container">
    <div class="brand-top">
        <div class="page-desc"><?= $pageInfo->getData('description') ?></div>
    </div>

    <div class="brand-main">
        <div class="block">
            <div class="block-content"><?= $block->getChildHtml(); ?></div>
        </div>
    </div>
</div>
