<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!doctype html>
<html <?= /* @noEscape */ $htmlAttributes ?>>
<head <?= /* @noEscape */ $headAttributes ?>>
    <?= /* @noEscape */ $requireJs ?>
    <?= /* @noEscape */ $headContent ?>
    <?php if (isset($headCritical)): ?>
        <?= /* @noEscape */ $headCritical ?>
    <?php endif; ?>
    <?php if (isset($headAssets)): ?>
        <?= /* @noEscape */ $headAssets ?>
    <?php endif; ?>
    <?= /* @noEscape */ $headAdditional ?>
</head>
<body data-container="body"
      data-mage-init='{"loaderAjax": {}, "loader": { "icon": "#"}}'
    <?= /* @noEscape */ $bodyAttributes ?>>
    <?= /* @noEscape */ $layoutContent ?>
</body>
</html>
