<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\LoginAsCustomerAssistance\Api\IsAssistanceEnabledInterface;
use Magento\LoginAsCustomerAssistance\ViewModel\ShoppingAssistanceViewModel;

/** @var Escaper $escaper */
/** @var ShoppingAssistanceViewModel $viewModel */
$viewModel = $block->getViewModel();

if ($viewModel->isLoginAsCustomerEnabled()): ?>
    <script type="text/x-magento-init">
    {
        ".form-create-account, .form-edit-account": {
            "Magento_LoginAsCustomerAssistance/js/opt-in": {
                "allowAccess": "<?= /* @noEscape */ IsAssistanceEnabledInterface::ALLOWED ?>",
                "denyAccess": "<?= /* @noEscape */ IsAssistanceEnabledInterface::DENIED ?>"
            }
        }
    }
    </script>
    <div class="field choice">
        <input type="checkbox"
               name="assistance_allowed_checkbox"
               title="<?= $escaper->escapeHtmlAttr(__($viewModel->getAssistanceCheckboxTitle())) ?>"
               value="1"
               id="assistance_allowed_checkbox"
               <?php if ($viewModel->isAssistanceAllowed()): ?>checked="checked"<?php endif; ?>
               class="checkbox">
        <label for="assistance_allowed_checkbox" class="label">
            <span class="mb-tooltip" title="<?= $escaper->escapeHtmlAttr(__($viewModel->getAssistanceCheckboxTooltip())) ?>"><?= $escaper->escapeHtmlAttr(__($viewModel->getAssistanceCheckboxTitle())) ?></span>
        </label>

        <input type="hidden" name="assistance_allowed" value=""/>
    </div>
<?php endif ?>
