<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$_mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$id = $block->getGalleryId().$block->getProduct()->getId();
$images = $block->getGalleryImages()->getItems();
$imgCount = count($images);
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $this->helper('Magento\Catalog\Helper\Image');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

//$thumbType = $_mbHelper->getConfig('mbconfig/product_view/nav_dir');
$thumbType = 'vertical';
$rtl = $_mbHelper->getConfig('mbdesign/general/enable_rtl');
$imgs = '';
$pl = '';
if ($imgCount > 1) {
    $imgs = 'imgs';
    $pl = '<span class="thumb-pl"></span>';
}
$width = $block->getImageAttribute('product_page_image_medium', 'width');
$height = $block->getImageAttribute('product_page_image_medium', 'height') ?: $width;
$thumbWidth = $block->getImageAttribute('product_page_image_small', 'width');
$thumbHeight = $block->getImageAttribute('product_page_image_small', 'height');
$ratio = round($height / $width, 4);
$pad = $ratio * 100 . '%';

$thumbW = 66;
$thumbH = $thumbW * $ratio;
?>
<div class="gallery-placeholder _block-content-loading gallery-<?= $id; ?> <?= $thumbType ?> <?= $imgs ?>"
     data-gallery-role="gallery-placeholder"
     style="--ratio:<?= $ratio ?>;--pad-product:<?= $pad ?>;--pad-thumb:<?= $thumbH ?>px">
    <div class="gallery-placeholder__image">
        <img
            alt="main product photo"
            class="img-fluid"
            src="<?= /* @noEscape */ $mainImageData ?>"
            width="<?= $width ?>"
            height="<?= $height ?>"
        />
        <?= $pl ?>
    </div>
</div>
<script>
    function addStyleSheet () {
        var ss = document.styleSheets;
        for (var i = 0, max = ss.length; i < max; i++) {
            if (ss[i].href && ss[i].href.indexOf('mage/gallery/gallery') !== -1)
                return;
        }
        var link = document.createElement("link");
        link.rel = "stylesheet";
        link.media = "all";
        link.href = "<?= $block->getViewFileUrl('mage/gallery/gallery.css') ?>";

        document.getElementsByTagName("head")[0].appendChild(link);
    }
    addStyleSheet();
</script>
<script type="text/x-magento-init">
    {
        ".gallery-<?= $id; ?>": {
            "mage/gallery/gallery": {
                "data": <?= $block->getGalleryImagesJson() ?>,
                "options": {
                    "thumbmargin": 10,
                    "thumbborderwidth": 1,
                    "nav": "thumbs",
                    "loop": 1,
                    "keyboard": 1,
                    "arrows": 0,
                    "allowfullscreen": <?= (int)$_mbHelper->getConfig('mbconfig/product_view/allowfullscreen') ?>,
                    "showCaption": 0,
                    "width": "<?= $width ?>",
                    "thumbwidth": <?= $thumbW ?>,
                    "thumbheight": <?= $thumbH ?>,
                    "height": <?= $height ?>,
                    "transitionduration": <?= (int)$_mbHelper->getConfig('mbconfig/product_view/gallery_duration') ?>,
                    "transition": "<?= $_mbHelper->getConfig('mbconfig/product_view/gallery_effect') ?>",
                    "navarrows": 1,
                    "navtype": "slides",
                    "navdir": "<?= $thumbType ?>",
                    "direction": "<?= $rtl ? 'rtl' : 'ltr'?>"
                },
                "fullscreen": {
                    "nav": "thumbs",
                    "loop": 1,
                    "navdir": "vertical",
                    "navarrows": 0,
                    "navtype": "slides",
                    "arrows": 1,
                    "showCaption": 1,
                    "transitionduration": 600,
                    "transition": "crossfade"
                },
                "breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"nav":"thumbs","navdir":"horizontal"}}}}
            }
        }
    }
</script>
