<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */

$mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$isTab = $mbHelper->getConfig('mbconfig/product_view/product_tab');
$isViewMore = (int)$mbHelper->getConfig('mbconfig/product_view/view_more_description');
$stickyAddCart = (int)$mbHelper->getConfig('mbconfig/product_view/sticky_add_cart');
$maxHeight = (int)$mbHelper->getConfig('mbconfig/product_view/description_max_height') ?: 250;

if ($isTab) {
    $class = 'product-tab';
    $initJs = '{"tabs":{"openedState":"opened","animate":{"duration": 300}}}';
} else {
    $class = 'product-accordion';
    $active = (string)$mbHelper->getConfig('mbconfig/product_view/open_accordion');
    if (!strpos($active, ',')) {
        $active = '0';
    }
    $initJs = '{"accordion":{"openedState":"opened","active":['.$active.'],"collapsible":true,"multipleCollapsible":true,"animate":{"duration":300}}}';
}
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed <?= $class ?>">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='<?= $initJs ?>'>
            <?php $i = 0; ?>
            <?php foreach ($detailedInfoGroup as $name) : ?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');

                    $open = '';
                    if ((!$isTab && in_array($i, explode(',', $active))) || ($isTab && $i == 0)) {
                        $open = 'opened';
                    }
                ?>
                <div class="data item title <?= $open ?>"
                     data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= $block->escapeHtmlAttr($alias) ?>"
                       id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">
                        <?= /* @noEscape */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content"
                <?php if ($alias == 'description') : ?> style="--desc-max-height:<?= /* @noEscape */ $isViewMore ?
                $maxHeight . 'px' : 'none' ?>" <?php endif ?>>
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php $i++; ?>
            <?php endforeach;?>
        </div>
    </div>

    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Catalog/js/product/product-detail": {
                "isViewMore": <?= $isViewMore ?>,
                "maxHeight": <?= $maxHeight ?>,
                "stickyAddCart": <?= $stickyAddCart ?>
            }
        }
    }
</script>
<?php endif; ?>
