<?php

$subscriptions = $block->getActiveSubscriptions();
$paymentMethods = $block->getCustomerPaymentMethods();
$canceledSubscriptions = $block->getCanceledSubscriptions();

/** @var \StripeIntegration\Payments\Block\Customer $block */

if (empty($subscriptions)): ?>
<div class="message info empty">
  <span><?= $block->escapeHtml(__("You do not have any active subscriptions.")); ?></span>
</div>
  <?php if (!empty($canceledSubscriptions)): ?>
    <div class="table-wrapper stripe-subscriptions">
      <table class="data table table-order-items history" id="my-orders-table">
        <?= /* @noEscape */ $block->getCanceledSubscriptionsHtml(); ?>
      </table>
    </div>
  <?php endif; ?>
<?php else: ?>
  <div class="table-wrapper stripe-subscriptions">
    <table class="data table table-order-items history" id="my-orders-table">
      <caption class="table-caption"><?= $block->escapeHtml(__("Subscriptions")); ?></caption>
      <thead>
        <tr>
          <th scope="col" class="col order"><?= $block->escapeHtml(__("Order #")); ?></th>
          <th scope="col" class="col id"><?= $block->escapeHtml(__("Subscription")); ?></th>
          <th scope="col" class="col status"><?= $block->escapeHtml(__("Actions")); ?></th>
        </tr>
      </thead>
      <tbody>
  <?php foreach ($subscriptions as $subscription): ?>
    <?php
      /** @var \StripeIntegration\Payments\Model\Stripe\Subscription $stripeSubscriptionModel */
      $stripeSubscriptionModel = $block->getSubscriptionModel($subscription);
      ?>
        <tr class="<?= $block->escapeHtmlAttr($subscription->id); ?>">
          <td data-th="Order #" class="col order">
            <a href="viewOrder/<?= $block->escapeHtmlAttr($subscription->metadata["Order #"]); ?>">
              <?= $block->escapeHtml($subscription->metadata["Order #"]); ?>
            </a>
          </td>
          <td data-th="<?= $block->escapeHtmlAttr(__("Subscription")); ?>" class="col id">
            <div class="subscription-name">
              <?= $block->escapeHtml($block->getSubscriptionName($subscription)); ?>
            </div>
            <div class="billed">
              <?= /* @noEscape */ $stripeSubscriptionModel->getFormattedBilling(); ?>
            </div>
            <div class="<?= $block->escapeHtmlAttr($subscription->id); ?> payment-method stripe-subscription-edit">
              <div class="static section">
                <div class="details stripe-payments">
                  <?php $paymentMethod = $block->getSubscriptionDefaultPaymentMethod($subscription); ?>
                  <?php if ($paymentMethod): ?>
                    <img class="icon" src="<?= $block->escapeHtmlAttr($paymentMethod['icon']); ?>" alt="<?= $block->escapeHtmlAttr($paymentMethod['label']); ?>">
                    <span class="label"><?= $block->escapeHtml($paymentMethod['label']); ?></span>
                    <?php if (!empty($paymentMethod['exp_month'])): ?>
                      <span class="exp">
                        <?= $block->escapeHtml($paymentMethod['exp_month']); ?>/<?= $block->escapeHtml($paymentMethod['exp_year']); ?>
                      </span>
                    <?php endif; ?>
                  <?php else: ?>
                    <?= $block->escapeHtml(__("No payment method.")); ?>
                  <?php endif; ?>
                </div>
              </div>
              <div class="mutable section">
                <b><?= $block->escapeHtml(__("Select a payment method:")); ?></b><br>

                <form method="POST" action="<?= $block->escapeUrl($block->getUrl('stripe/subscriptions/changepaymentmethod')); ?>">
                  <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()); ?>">
                  <input type="hidden" name="subscription_id" value="<?= $block->escapeHtmlAttr($subscription->id); ?>">
                  <div class="details">
                    <?php $paymentMethodId = $block->getSubscriptionPaymentMethodId($subscription); ?>
                    <?php foreach ($paymentMethods as $paymentMethod): ?>
                      <div class="subscription-payment-method stripe-payments">
                        <input type="radio" id="<?= $block->escapeHtmlAttr($subscription->id . "_" . $paymentMethod['id']); ?>"
                              name="payment_method_id"
                              value="<?= $block->escapeHtmlAttr($paymentMethod['id']); ?>"
                              <?php if ($paymentMethodId == $paymentMethod['id']) echo "checked"; ?>>

                        <label for="<?= $block->escapeHtmlAttr($subscription->id . "_" . $paymentMethod['id']); ?>">
                          <img class="icon" src="<?= $block->escapeHtmlAttr($paymentMethod['icon']); ?>" alt="<?= $block->escapeHtmlAttr($paymentMethod['label']); ?>">
                          <span class="label"><?= $block->escapeHtml($paymentMethod['label']); ?></span>
                          <?php if (!empty($paymentMethod['exp_month'])): ?>
                            <span class="exp">
                              <?= $block->escapeHtml($paymentMethod['exp_month']); ?>/<?= $block->escapeHtml($paymentMethod['exp_year']); ?>
                            </span>
                          <?php endif; ?>
                        </label>
                      </div>
                    <?php endforeach; ?>
                  </div>
                  <div class="actions">
                    <button type="submit" class="action primary"><?= $block->escapeHtml(__("Save")); ?></button>
                    <button type="button" onclick="cancelEditSubscription('<?= $block->escapeJs($subscription->id); ?>')">
                      <?= $block->escapeHtml(__("Cancel")); ?>
                    </button>
                    <?= $block->escapeHtml(__("or")); ?>
                    <a href="<?= $block->escapeUrl($block->getUrl('stripe/customer/paymentmethods')); ?>"><?= $block->escapeHtml(__("add a new method")); ?></a>
                  </div>
                </form>
              </div>
            </div>
          </td>
          <td data-th="Actions" class="col">
            <div class="stripe-actions-dropdown">
              <span class="action toggle" data-toggle="dropdown" aria-haspopup="true"
                data-mage-init='{"dropdown":{}}'
                >
                <span>
                  <svg aria-hidden="true" class="SVGInline-svg SVGInline--cleaned-svg SVG-svg Icon-svg Icon--more-svg Button-icon-svg Icon-color-svg Icon-color--inherit-svg" height="16" width="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm6 0a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm6 0a2 2 0 1 1 0-4 2 2 0 0 1 0 4z" fill-rule="evenodd"></path></svg>
                </span>
              </span>
              <ul class="dropdown-options" data-target="dropdown">
                <?php if ($stripeSubscriptionModel->canUpgradeDowngrade()): ?>
                    <li>
                      <form method="POST" action="<?= $block->escapeUrl($block->getUrl('stripe/subscriptions/change')); ?>">
                        <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()); ?>">
                        <input type="hidden" name="subscription_id" value="<?= $block->escapeHtmlAttr($subscription->id); ?>">
                        <button type="submit" class="action alink stripe-link"><?= $block->escapeHtml(__('Change subscription')); ?></button>
                      </form>
                    </li>
                <?php endif; ?>
                <li>
                  <span class="item" onclick="javascript:editSubscription('<?= $block->escapeJs($subscription->id); ?>', 'payment-method')">
                    <a href="javascript:void(0);"><?= $block->escapeHtml(__("Change payment method")); ?></a>
                  </span>
                </li>
                <?php if ($stripeSubscriptionModel->canChangeShipping()): ?>
                <li>
                  <span class="item">
                    <form method="POST" action="<?= $block->escapeUrl($block->getUrl('stripe/subscriptions/changeshipping')); ?>">
                      <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()); ?>">
                      <input type="hidden" name="subscription_id" value="<?= $block->escapeHtmlAttr($subscription->id); ?>">
                      <button type="submit" class="action alink stripe-link"><?= $block->escapeHtml(__('Change shipping details')); ?></button>
                    </form>
                  </span>
                </li>
                <?php endif; ?>
                <li class="cancel">
                  <span class="item">
                    <form method="POST" action="<?= $block->escapeUrl($block->getUrl('stripe/subscriptions/cancel')); ?>">
                      <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()); ?>">
                      <input type="hidden" name="subscription_id" value="<?= $block->escapeHtmlAttr($subscription->id); ?>">
                      <button type="submit" class="action delete stripe-link"><?= $block->escapeHtml(__('Cancel subscription')); ?></button>
                    </form>
                  </span>
                </li>
              </ul>
            </div>
          </td>
        </tr>
  <?php endforeach; ?>
        <?= /* @noEscape */ $block->getCanceledSubscriptionsHtml(); ?>
      </tbody>
    </table>
  </div>
<?php endif; ?>

<script type="application/javascript">

    var editSubscription = function(subscriptionId, section)
    {
        jQuery('.stripe-subscription-edit .mutable.section', 'tr.'+subscriptionId).hide();
        jQuery('.stripe-subscription-edit.'+section+'.'+subscriptionId+' .mutable.section', 'tr.'+subscriptionId).show();
        jQuery('.stripe-subscription-edit.'+subscriptionId+' .static.section', 'tr.'+subscriptionId).hide();
    };

    var cancelEditSubscription = function(subscriptionId)
    {
        jQuery('.stripe-subscription-edit.'+subscriptionId+' .mutable.section', 'tr.'+subscriptionId).hide();
        jQuery('.stripe-subscription-edit.'+subscriptionId+' .static.section', 'tr.'+subscriptionId).show();
    };

    require(['domReady!', 'jquery', 'mage/translate', 'Magento_Customer/js/customer-data', 'mage/mage'], function(domReady, $, $t, customerData)
    {
      customerData.initStorage();
      customerData.invalidate(['cart', 'cart-data', 'checkout-data']);
      // customerData.reload(['cart'], true);

      $("button.update").click(function(e){
        customerData.invalidate(['cart']);
        // customerData.reload(['cart'], true);
      });
    });
</script>
