<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<div class="gallery-placeholder _block-content-loading" id="quickview-gallery" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader"></div>
    </div>
</div>
<!--Fix for jumping content. Loader must be the same size as gallery.-->
<script>
    function addStyleSheet () {
        var ss = document.styleSheets;
        for (var i = 0, max = ss.length; i < max; i++) {
            if (ss[i].href && ss[i].href.indexOf('mage/gallery/gallery') !== -1)
                return;
        }
        var link = document.createElement("link");
        link.rel = "stylesheet";
        link.media = "all";
        link.href = "<?= $block->getViewFileUrl('mage/gallery/gallery.css') ?>";

        document.getElementsByTagName("head")[0].appendChild(link);
    }
    addStyleSheet();
</script>
<script>
    var config = {
            "width": <?= /* @noEscape */ $block->getImageAttribute('product_page_image_medium', 'width') ?>,
            "thumbheight": <?php /* @noEscape */ echo $block->getImageAttribute('product_page_image_small', 'height')
                ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
            "navtype": "<?= /* @noEscape */ $block->getVar("gallery/navtype") ?>",
            "height": <?= /* @noEscape */ $block->getImageAttribute('product_page_image_medium', 'height') ?>
        },
        thumbBarHeight = 0,
        loader = document.querySelectorAll('#quickview-gallery [data-role="loader"]')[0];

    if (config.navtype === 'horizontal') {
        thumbBarHeight = config.thumbheight;
    }

    loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
</script>
<script type="text/x-magento-init">
    {
        "#quickview-gallery": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "<?= /* @noEscape */ $block->getVar("gallery/nav") ?>",
                    "loop": <?= /* @noEscape */ $block->getVar("gallery/loop") ? 'true' : 'false' ?>,
                    "keyboard": <?= /* @noEscape */ $block->getVar("gallery/keyboard") ? 'true' : 'false' ?>,
                    "arrows": <?= /* @noEscape */ $block->getVar("gallery/arrows") ? 'true' : 'false' ?>,
                    "allowfullscreen": <?= /* @noEscape */ $block->getVar("gallery/allowfullscreen") ? 'true' : 'false' ?>,
                    "showCaption": <?= /* @noEscape */ $block->getVar("gallery/caption") ? 'true' : 'false' ?>,
                    "width": "<?= /* @noEscape */ $block->getImageAttribute('product_page_image_medium', 'width') ?>",
                    "thumbwidth": "<?= /* @noEscape */ $block->getImageAttribute('product_page_image_small', 'width') ?>",
                    <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                        "thumbheight": <?php /* @noEscape */ echo $block->getImageAttribute('product_page_image_small', 'height')
        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                        "height": <?php /* @noEscape */ echo $block->getImageAttribute('product_page_image_medium', 'height')
        ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?= /* @noEscape */ $block->getVar("gallery/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @noEscape */ $block->getVar("gallery/transition/effect") ?>",
                    "navarrows": <?= /* @noEscape */ $block->getVar("gallery/navarrows") ? 'true' : 'false' ?>,
                    "navtype": "<?= /* @noEscape */ $block->getVar("gallery/navtype") ?>",
                    "navdir": "<?= /* @noEscape */ $block->getVar("gallery/navdir") ?>"
                },
                "fullscreen": {
                    "nav": "<?= /* @noEscape */ $block->getVar("gallery/fullscreen/nav") ?>",
                    "loop": <?= /* @noEscape */ $block->getVar("gallery/fullscreen/loop") ? 'true' : 'false' ?>,
                    "navdir": "<?= /* @noEscape */ $block->getVar("gallery/fullscreen/navdir") ?>",
                    "navarrows": <?= /* @noEscape */ $block->getVar("gallery/fullscreen/navarrows") ? 'true' : 'false' ?>,
                    "navtype": "<?= /* @noEscape */ $block->getVar("gallery/fullscreen/navtype") ?>",
                    "arrows": <?= /* @noEscape */ $block->getVar("gallery/fullscreen/arrows") ? 'true' : 'false' ?>,
                    "showCaption": <?= /* @noEscape */ $block->getVar("gallery/fullscreen/caption") ? 'true' : 'false' ?>,
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?= /* @noEscape */ $block->getVar("gallery/fullscreen/transition/duration")
        ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @noEscape */ $block->getVar("gallery/fullscreen/transition/effect") ?>"
                },
                "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
