<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var Magento\Checkout\Block\Cart\Sidebar $block */
/** @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div class="col col-minicart">
    <div class="minicart-action">
        <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
           data-bind="scope: 'minicart_content'" aria-label="<?= $block->escapeHtml(__('My Cart')) ?>">
            <i class="mbi mbi-bag2"></i>
            <span class="counter qty empty"
                  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                <span class="counter-number" data-bind="html: getCartParam('summary_count') > 9 ? '&nbsp;9<sup>+</sup>' : getCartParam('summary_count')"></span>
            </span>
        </a>
    </div>
    <div data-block="minicart" class="minicart-wrapper minicart-slide mfp-hide">
        <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-minicart empty" style="display: block;">
                <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <?= $block->getChildHtml('minicart.addons') ?>
            </div>
        <?php endif ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
            /* @noEscape */ $block->getSerializedConfig(), false); ?>
        <script type="text/x-magento-init">
            {
                "[data-block='minicart']": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                },
                "*": {
                    "Magento_Ui/js/block-loader": "#"
                }
            }
        </script>
    </div>
</div>
