<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var $block Magento\ReCaptchaUi\Block\ReCaptcha */
/** @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div
    class="field-recaptcha"
    id="<?= /* @noEscape */ $block->getRecaptchaId() ?>-container"
    data-bind="scope:'<?= /* @noEscape */ $block->getRecaptchaId() ?>'"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<?php
$scriptString = <<<script
    require(['jquery', 'domReady!'], function ($) {
        $('#{$block->getRecaptchaId()}-container')
            .appendTo('#newsletter-validate-detail');
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<script type="text/x-magento-init">
{
    "#<?= /* @noEscape */ $block->getRecaptchaId() ?>-container": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
